# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/a32e/setup-makefiles.sh

PRODUCT_COPY_FILES += \
vendor/htc/a32e/proprietary/app/TimeService/TimeService.apk:system/bin/app/TimeService/TimeService.apk \
    vendor/htc/a32e/proprietary/bin/audioflacapp:system/bin/audioflacapp \
    vendor/htc/a32e/proprietary/bin/qti:system/bin/qti \
    vendor/htc/a32e/proprietary/firmware/keymaster.b00:system/firmware/keymaster.b00 \
    vendor/htc/a32e/proprietary/firmware/keymaster.b01:system/firmware/keymaster.b01 \
    vendor/htc/a32e/proprietary/firmware/keymaster.b02:system/firmware/keymaster.b02 \
    vendor/htc/a32e/proprietary/firmware/keymaster.b03:system/firmware/keymaster.b03 \
    vendor/htc/a32e/proprietary/firmware/keymaster.mdt:system/firmware/keymaster.mdt \
    vendor/htc/a32e/proprietary/firmware/libpn547_fw.so:system/firmware/libpn547_fw.so \
    vendor/htc/a32e/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/htc/a32e/proprietary/lib/egl/eglsubAndroid.so:system/bin/egl/eglsubAndroid.so \
    vendor/htc/a32e/proprietary/lib/egl/libEGL_adreno.so:system/bin/egl/libEGL_adreno.so \
    vendor/htc/a32e/proprietary/lib/egl/libGLESv1_CM_adreno.so:system/bin/egl/libGLESv1_CM_adreno.so \
    vendor/htc/a32e/proprietary/lib/egl/libGLESv2_adreno.so:system/bin/egl/libGLESv2_adreno.so \
    vendor/htc/a32e/proprietary/lib/egl/libq3dtools_adreno.so:system/bin/egl/libq3dtools_adreno.so \
    vendor/htc/a32e/proprietary/lib/mediadrm/libdrmclearkeyplugin.so:system/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/htc/a32e/proprietary/lib/qcdrm/playready/lib/drm/libdrmprplugin_customer.so:system/lib/qcdrm/playready/lib/drm/libdrmprplugin_customer.so \
    vendor/htc/a32e/proprietary/lib/qcdrm/playready/lib/mediadrm/libprmediadrmdecrypt_customer.so:system/lib/qcdrm/playready/lib/mediadrm/libprmediadrmdecrypt_customer.so \
    vendor/htc/a32e/proprietary/lib/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so:system/lib/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so \
    vendor/htc/a32e/proprietary/lib/qcdrm/playready/lib/libprdrmdecrypt_customer.so:system/lib/qcdrm/playready/lib/libprdrmdecrypt_customer.so \
    vendor/htc/a32e/proprietary/lib/qcdrm/playready/lib/libtzplayready_customer.so:system/lib/qcdrm/playready/lib/libtzplayready_customer.so \
    vendor/htc/a32e/proprietary/lib/soundfx/libqcbassboost.so:system/lib/soundfx/libqcbassboost.so \
    vendor/htc/a32e/proprietary/lib/soundfx/libqcreverb.so:system/lib/soundfx/libqcreverb.so \
    vendor/htc/a32e/proprietary/lib/soundfx/libqcvirt.so:system/lib/soundfx/libqcvirt.so \

# Media
PRODUCT_COPY_FILES += \
    vendor/htc/a32e/proprietary/media/LMspeed_508.emd:system/media/LMspeed_508.emd \
    vendor/htc/a32e/proprietary/media/PFFprec_600.emd:system/media/PFFprec_600.emd \

# libs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/htc/a32e/proprietary/lib,system/lib)
